### ISSUE TITLE
What is the meaning of `{ delta: ... }`?

### ISSUE THREAD

**Issue by renatoargh** [Daplie/node-authenticator#3]
Hi, thanks for you awesome work! Can you explain what is the meaning of all the possible values for delta? It can be `-1`, `0` and `1`. All of these 3 options means success? What is the difference between them? Thank you a lot.

**Comment by renatoargh** [comment]
Thank you a lot! I suggest you to add this info on the docs! :)

**Comment by coolaj86** [comment]
PR would be welcome: https://git.daplie.com/Daplie/node-authenticator
